### ISSUE TITLE
Build error 

### ISSUE THREAD

**Issue by bsia** [kaushikgopal/movies-usf-android#18]
When I try to build this on Android Studio 3.3.2, I get an error:

    > Task :app:kaptReleaseKotlin FAILED
    e: /Users/barry.sia/src/open/movies-usf/app/build/tmp/kapt3/stubs/release/co/kaush/msusf/MSApp.java:6: error: incompatible types: NonExistentClass cannot be converted to Annotation
    @error.NonExistentClass()
          ^
        e: /Users/barry.sia/src/open/movies-usf/app/build/tmp/kapt3/stubs/release/co/kaush/msusf/movies/MSMovieRepository.java:6: 
    error: incompatible types: NonExistentClass cannot be converted to Annotation
    @error.NonExistentClass()
          ^

**Comment by kaushikgopal** [comment]
hey @bsia project has undergone a lot of changes, want to give it a shot and let me know if you're still running into build issues?
