### ISSUE TITLE
[Enhancement] In-place member functions on Result to State and Effect

### ISSUE THREAD

**Issue by Ethan1983** [kaushikgopal/movies-usf-android#20]
Just a thought for folks using this pattern.

Instead of having this nested when statements for Result to State and Result to Effect conversion, base Result could have functions to convert it to State (given current state) and to Effect.

With this in place, VM can just invoke a generic result.toState(currentState) and result.toEffect(). Any new Event and Result can be coded in place without having the lengthy conversion function. VM will just need additional logic to convert event to results.

**Comment by kaushikgopal** [comment]
good idea @Ethan1983 !
