### ISSUE TITLE
Partial UI update with a wrapper

### ISSUE THREAD

**Issue by susonthapa** [kaushikgopal/movies-usf-android#23]
Hello kaushik, I have a question regarding the unidirectional state flow architecture. The implementation that you have done with rxjava in movies-usf is really good
, really appreciated that. One of my confusion  is the way we pass the view state from viewmodel. Since, you are passing the entire state from the ViewModel, if the state is complex, then even a small change like changing the title can render the entire view. I also followed https://github.com/kaushikgopal/movies-usf-android/issues/14 where you mentioned of using diffing tool. I was wandering if we could use some wrapper around each attributes in the viewstate like NullBox (for nullables in rxjava) to identify if the state has changed or not, may be a wrapper with a boolean? This way we can check in the view weather the attributes in the state has changed or not and render only the changed ones.

**Comment by susonthapa** [comment]
Anyone having this same question, I have written [this](https://medium.com/swlh/yet-another-uni-directional-state-flow-architecture-in-android-6957f5f3b37b) blog post that explains the concept with a sample app.

**Comment by kaushikgopal** [comment]
🙏 thanks for the detail article and post @susonthapa . i just read it - really good stuff!

this was a question i get frequently regarding this implementation. you're right in that my response was use a type of `DiffUtils` implementation but I also was banking of Jetpack Compose to just magically take care of a lot of this and in 2022, i'm glad that seems to be the case 😅 .

Either way, thanks for the informative post.
