### ISSUE TITLE
how to 

### ISSUE THREAD

**Issue by aplha98** [kaushikgopal/movies-usf-android#37]
why not using the scan operator instead of  
private val _viewState = MutableStateFlow(initialState)
override val viewState = _viewState.asStateFlow()

**Comment by kaushikgopal** [comment]
@aplha98 `MutableStateFlow`s [require an initial state](https://github.com/Kotlin/kotlinx.coroutines/blob/master/kotlinx-coroutines-core/common/src/flow/StateFlow.kt#L187).

feel free to reopen if you have follow up questions on this.
